### PR TITLE
Add system properties substitution.

### PR DESCRIPTION
**Pull request by giamma**
Proposed changes for #17

### CODE REVIEW

**Comment by h-thurow** [comment]
Thanks for your help! 

To not lose the chance to replace the current substitution implementation with Commons Configuration I would suggest to set the variable prefix to "${sys:", so it is compatible with Commons Configuration's variable Interpolation. See [Basic features and AbstractConfiguration > Variable Interpolation](http://commons.apache.org/proper/commons-configuration/userguide/howto_basicfeatures.html#Basic_features_and_AbstractConfiguration).

**Comment by giamma** [comment]
I am not familiar with Commons Configuration.
I used StrSubstitutor from Commons Lang because I noticed that Commons Lang was already a dependency of Simple JNDI.

Do you mean that commons configuration has a similar utility for system property substitution and you would prefer the code to use that one in place of StrSubstitutor from Commons Lang? 

I don't think StrSubstitutor supports a prefix like "sys:", but alternatively I could change the code to get the system properties, rebind them into a new Properties with the "sys" prefix and pass the new Properties to StrSubstitor. Or do you have a better idea?

**Comment by h-thurow** [comment]
Commons Configuration is really powerfull. So I think about using it in Simple-JNDI. You can configure the prefix used by StrSubstitutor to identify variables this way:

        StrSubstitutor substitutor = new StrSubstitutor(StrLookup.systemPropertiesLookup());
        substitutor.setVariablePrefix("${sys:");
        assertEquals("/Users/holger", substitutor.replace("${sys:user.home}"));

So whenever I am going to introduce Commons Configuration into Simple-JNDI property files need not to be changed.

**Comment by giamma** [comment]
OK, got it, I'll update the pull request.

**Comment by giamma** [comment]
Any feedback?

**Pull request merged**
