### PR TITLE
Add support for tomcat factory attribute

### PR DESCRIPTION
**Pull request by m-kalai**
If you're trying to migrate Resources from Tomcat context you might come across "**factory**" attribute which specifies object factory. When you have multiple resources with different **type**s you can't use `java.naming.factory.object` as often wrong factory object is used. This change allows you to specify correct factory and create these objects.

Example:
```
amqp/connection/type=a.b.c.ConnectionWrapper
amqp/connection/factory=a.b.c.ConnectionFactory
amqp/connection/host=localhost
amqp/connection/port=5672
```

### CODE REVIEW

**Comment by h-thurow** [comment]
Could you please provide an example where a wrong ObjectFactory is used?

**Comment by m-kalai** [comment]
Short answer, when you provide multiple classes/factories in `java.naming.factory.object`. This way there is no control over which factory is called for which type.

I haven't figured out how to provide different factories for different sub-contexts with simple-jndi config properties, but with this small change it works quite nicely.

Just in case i'll try to illustrate the situation bit more. Imagine that you have some spring app and you have 2 beans with 2 different types.
```
<jee:jndi-lookup id="bean1" jndi-name="java:comp/env/xxx/connection" expected-type="a.b.c.X"/>
<jee:jndi-lookup id="bean2" jndi-name="java:comp/env/zzz/connection" expected-type="a.b.c.Z"/>
```
In your JNDI context you provide something like 
```
xxx/connection/type=a.b.c.X
xxx/connection/factory=a.b.c.FactoryX
xxx/connection/port=8888

zzz/connection/type=a.b.c.Z
zzz/connection/factory=a.b.c.FactoryZ
zzz/connection/port=9000
zzz/connection/property=something
```
In your `jndi.properties` you specify:
```
java.naming.factory.object=a.b.c.FactoryX:a.b.c.FactoryZ
```

What happens is that for `bean1` everything will be ok. `JndiLoader` calls `javax.naming.spi.NamingManager#getObjectInstance` which takes `Reference` and first factory `a.b.c.FactoryX` and returns object of type `a.b.c.X`. 
Problem is that `bean2` also tries first factory and **succeeds**!
It succeeds because properties are somewhat similar and it's able to create the object. But the object is of type `a.b.c.X` instead of `a.b.c.Z` and you get something like 
```
Caused by: org.springframework.jndi.TypeMismatchNamingException: Object of type [class a.b.c.X] available at JNDI location [java:comp/env/zzz/connection] is not assignable to [a.b.c.Z]
```

Does that make sense?

I could override/hack `JndiUtils` class to make it work for my project but I thought people might benefit from this, and the price is just one more reserved word - factory.

**Comment by h-thurow** [comment]
Please see [DemoBeanFactoryTest#severalObjectFactories](https://github.com/h-thurow/Simple-JNDI/blob/1b534cb95abd162ab98835719d520381e25b68de/src/test/java/spi/objectfactories/DemoBeanFactoryTest.java#L65), how to instantiate several beans with SPI.

**Comment by h-thurow** [comment]
> Problem is that bean2 also tries first factory and succeeds!

Each ObjectFactory has to check the type parameter, to see if it is responsible. See [DemoBeanFactory2#getObjectInstance](https://github.com/h-thurow/Simple-JNDI/blob/ac93cdaeb13664e3bd4860c956cfc40d59f75162/src/test/java/spi/objectfactories/DemoBeanFactory2.java#L25).

**Comment by m-kalai** [comment]
Exactly, it only works because object factories you use, have this specific check.
```
        String type = (String) ref.get("type").getContent();
        if (type.equals(DemoBean.class.getName())) {
```
https://github.com/h-thurow/Simple-JNDI/blob/master/src/test/java/spi/objectfactories/DemoBeanFactory.java#L25

That means problem is there and we just move the responsibility from the library to the ObjectFactory.

I don't have that choice. Factories I use are 3rd party and none of them have this check as they were used from Tomcat where "factory" attribute is a thing and there is no need for it. Also "type" attribute doesn't have to be provided by some JNDI implementations. I mean could you use this factory in Tomcat or Jboss? Can you do `ref.get("type").getContent()` too?

**Comment by h-thurow** [comment]
> Also "type" attribute doesn't have to be provided by some JNDI implementations.

To be standard compatible see [here](https://github.com/h-thurow/Simple-JNDI/blob/61e6e8784790a47f356f1671c723c70881672bd7/src/test/java/spi/objectfactories/DemoBeanFactory.java#L24).

**Comment by h-thurow** [comment]
> could you use this factory in Tomcat or Jboss?

No, of course. Tomcat and JBoss have heir own factory mechanisms, whereas SimpleJNDI relies on SPI.

**Comment by m-kalai** [comment]
Does that mean you don't want this feature? Or something similar so the user can have control instead of factory? 
So I either need to choose to rewrite those 3rd party factories or use different library instead of SimpleJDNI?

**Comment by m-kalai** [comment]
I mean I don’t really see the downside to being able to specify the object factory. Current behaviour is unaffected if somebody wants to use it.

**Comment by h-thurow** [comment]
Just out of curiosity, which factory do you want to use?

**Comment by m-kalai** [comment]
There is multiple factories we use, most of them proprietary. As I mentioned it's old Tomcat app being migrated.

But for example https://github.com/mongodb/mongo-java-driver/blob/master/driver-legacy/src/main/com/mongodb/client/jndi/MongoClientFactory.java

Some of them have some kind of check, some of them fail because of some missing property, and some of them return some generic interface type so you can have 2 beans with same interface/parent class but different factories. It's bit messy I agree.

Btw I noticed that there is support for "**converter**" property which I didn't see anywhere in the docs. This "**factory**" property is similar only it allows you use **existing** factories so you don't have to write loads of converters if you have same problem as me.

**Comment by m-kalai** [comment]
I'm willing to change my PR to your vision but I'd need to know if it's going to happen please. Because if not I should start working on some other solution.

**Comment by h-thurow** [comment]
Ok, now I see the problem. There are too many ObjectFactory implementations not fully supporting SPI why they can not be listed together in java.naming.factory.object property.

So your PR is welcomed. Just the property name "factory" is too common. It might interfere with existing configurations. I would prefer "javaxNamingSpiObjectFactory" to be explicit.

**Comment by m-kalai** [comment]
OK, I don't have a problem with this. I'll refactor it. 
Do you want me to add some test as well? If so in a new class or in some existing one.

**Comment by h-thurow** [comment]
Some Tests or at least one test would be nice. Also for demo purposes. I renamed a class for this. See [SpiObjectFactoryTest](https://github.com/h-thurow/Simple-JNDI/blob/master/src/test/java/spi/objectfactories/SpiObjectFactoryTest.java).

**Comment by m-kalai** [comment]
Ok, i pushed the changes. Hope it's ok now. 
Btw how long it approximately takes to get a new release?

**Comment by h-thurow** [comment]
Friday or Saturday.

**Comment by h-thurow** [comment]
0.21.0 is downloadable. Thanks for your help!

**Comment by m-kalai** [comment]
Thank you too 👍

**Pull request merged**
